!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  auto_exposure: false
  auto_gain: false
  auto_shutter: false
  auto_white_balance: true
  brightness: 6.2255859375
  enable_strobe1: false
  enable_trigger: false
  enable_trigger_delay: false
  exposure: 2.41363525390625
  format7_color_coding: raw16
  format7_roi_height: 0
  format7_roi_width: 0
  format7_x_offset: 0
  format7_y_offset: 0
  frame_rate: 20.0
  gain: 24.035350799560547
  gamma: 1.0
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      auto_exposure: false
      auto_gain: false
      auto_shutter: false
      auto_white_balance: true
      brightness: 6.2255859375
      enable_strobe1: false
      enable_trigger: false
      enable_trigger_delay: false
      exposure: 2.41363525390625
      format7_color_coding: raw16
      format7_roi_height: 0
      format7_roi_width: 0
      format7_x_offset: 0
      format7_y_offset: 0
      frame_rate: 20.0
      gain: 24.035350799560547
      gamma: 1.0
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      name: Default
      pan: 1
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      shutter_speed: 0.003029942512512207
      state: true
      strobe1_delay: 0.0
      strobe1_duration: 1.0
      strobe1_polarity: 0
      tilt: 0
      trigger_delay: 0.0
      trigger_mode: mode0
      trigger_parameter: 0
      trigger_polarity: 0
      trigger_source: gpio0
      type: ''
      video_mode: format7_mode3
      white_balance_blue: 556
      white_balance_red: 550
    state: []
  pan: 1
  shutter_speed: 0.003029942512512207
  strobe1_delay: 0.0
  strobe1_duration: 1.0
  strobe1_polarity: 0
  tilt: 0
  trigger_delay: 0.0
  trigger_mode: mode0
  trigger_parameter: 0
  trigger_polarity: 0
  trigger_source: gpio0
  video_mode: format7_mode3
  white_balance_blue: 556
  white_balance_red: 550
state: []
